# captcha Solver
captcha_solver:
    provider: "anti-captcha.com"  # Now only support anti-captcha.com
    apikey: ""

# Email Verify
email_verify:
    m.kuku.lu_token: "a"
    m.kuku.lu_sessionhash: "a"